# Generated by Django 5.0.9 on 2024-10-28 15:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Home Page', 'verbose_name_plural': 'Home Pages'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=wagtail.fields.StreamField([('banner_text', 3), ('link_information', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add your heading', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add sub heading', 'required': False}), 2: ('wagtail.blocks.RichTextBlock', (), {'editor': 'secondary', 'help_text': 'Add additional text', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('heading', 0), ('sub_heading', 1), ('description', 2)]], {'group': 'Card Blocks'}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the label of the link', 'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Internal Page'), ('external', 'External URL')], 'help_text': 'Select the type of link'}), 6: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select an internal page', 'page_type': [], 'required': False}), 7: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter an external URL', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('label', 4), ('link_type', 5), ('internal_page', 6), ('external_url', 7)]], {'group': 'Card Blocks'})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image_slider',
            field=wagtail.fields.StreamField([('image_slider', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': "Title for the image slider (Please add the '&lt;/br&gt;' tag where you want to break the line.)", 'required': False}), 1: ('wagtail.blocks.RichTextBlock', (), {'editor': 'secondary', 'help_text': 'Add additional text', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Main image of the slider', 'required': True}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.ListBlock', (3,), {'help_text': 'Up to 10 small images', 'max_num': 10, 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Enter the label of the link', 'required': False}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Internal Page'), ('external', 'External URL')], 'help_text': 'Select the type of link'}), 7: ('wagtail.blocks.PageChooserBlock', (), {'help_text': 'Select an internal page', 'page_type': [], 'required': False}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter an external URL', 'required': False}), 9: ('wagtail.blocks.StructBlock', [[('label', 5), ('link_type', 6), ('internal_page', 7), ('external_url', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'Add button/link information to this section', 'label': 'Add link details', 'max_num': 2, 'min_num': 0}), 11: ('wagtail.blocks.StructBlock', [[('title', 0), ('description', 1), ('main_image', 2), ('related_images', 4), ('links', 10)]], {})}),
        ),
    ]
