# Generated by Django 5.0.9 on 2024-10-30 09:57

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculamPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(blank=True, help_text='add name ', max_length=200)),
                ('video', wagtail.fields.StreamField([('videosession', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'name of lesson', 'required': True}), 1: ('wagtail.blocks.URLBlock', (), {'required': False}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('video', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {'help_text': 'Add lessons to this session', 'label': 'Add lessons'}), 4: ('wagtail.blocks.StructBlock', [[('lessons', 3)]], {})}, null=True)),
            ],
            options={
                'verbose_name': 'Curriculam Page',
                'verbose_name_plural': 'Curriculam Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
