# Generated by Django 5.0.9 on 2024-10-30 11:02

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0011_alter_coursepage_content'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculampage',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Select Course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Course.coursepage'),
        ),
        migrations.AlterField(
            model_name='curriculampage',
            name='video',
            field=wagtail.fields.StreamField([('videosession', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'name of lesson', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('lessons_count', 1), ('video', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'help_text': 'Add lessons to this session', 'label': 'Add lessons'}), 5: ('wagtail.blocks.StructBlock', [[('lessons', 4)]], {})}, null=True),
        ),
    ]
