# Generated by Django 5.0.9 on 2024-10-29 09:11

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='Please enter name', max_length=255)),
                ('nav_type', models.CharField(blank=True, choices=[('header', 'Header Navigation'), ('footer', 'Footer Navigation'), ('footer_links', 'Footer Links')], default='top', help_text='Navigation type', max_length=20, null=True)),
                ('menus', wagtail.fields.StreamField([('single_menu', 9), ('multiple_menu', 11), ('tabbed_menu', 17)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'enter title', 'required': False}), 1: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('text', 'Text Menu'), ('bordered_button', 'Bordered Button Menu'), ('filled_button', 'Filled Button Menu')], 'help_text': 'Menu type', 'max_length': 20, 'null': True}), 2: ('wagtail.blocks.CharBlock', (), {'required': True}), 3: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Internal Page'), ('external', 'External URL')]}), 4: ('wagtail.blocks.PageChooserBlock', (), {'page_type': [], 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Enter a unique key for this tab. This key will be used to link the                                                                                             menu to the corresponding section of the page.', 'label': 'Tab Key', 'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'editable': False, 'help_text': 'This field can be avoided and will be set automatically.', 'label': 'Page name(internal)', 'max_length': 150, 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 2), ('link_type', 3), ('internal_page', 4), ('tab_key', 5), ('external_url', 6), ('internal_page_model_name', 7)]], {}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('menu_type', 1), ('menu_item', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (8,), {}), 11: ('wagtail.blocks.StructBlock', [[('title', 0), ('menu_type', 1), ('menu_item', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': 'Please enter tab name', 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': 'Please enter tab name', 'required': False}), 14: ('wagtail.blocks.CharBlock', (), {'help_text': 'Please provide unique slug name for url', 'required': False}), 15: ('wagtail.blocks.StructBlock', [[('title', 13), ('slug', 14), ('menu_items', 10)]], {}), 16: ('wagtail.blocks.ListBlock', (15,), {}), 17: ('wagtail.blocks.StructBlock', [[('title', 12), ('tabs', 16)]], {})})),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
