# Generated by Django 5.0.9 on 2024-10-29 11:22

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(help_text='Please enter name', max_length=250)),
                ('copyright', wagtail.fields.RichTextField(blank=True, help_text='Please enter copyright')),
                ('content', wagtail.fields.StreamField([('contact_info', 25)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Heading add here', 'max_length': 250, 'required': False}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'street address', 'max_length': 250, 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'add footer phone number', 'max_length': 20, 'required': True}), 3: ('wagtail.blocks.EmailBlock', (), {'help_text': 'add footer email address', 'required': True}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Add Name of teachers', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'domain', 'required': True}), 6: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 7: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('instagram', 'Instagram'), ('youtube', 'YouTube')], 'help_text': 'Select the social media platform'}), 8: ('wagtail.blocks.URLBlock', (), {'help_text': 'Enter the URL of the social media profile', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('platform', 7), ('url', 8)]], {}), 10: ('wagtail.blocks.ListBlock', (9,), {'help_text': 'Add button/link information to this section', 'label': 'Add link details', 'max_num': 3, 'min_num': 0}), 11: ('wagtail.blocks.StructBlock', [[('name', 4), ('domain', 5), ('image', 6), ('icons', 10)]], {}), 12: ('wagtail.blocks.ListBlock', (11,), {'help_text': 'Add the social media platforms and URLs you want to display.'}), 13: ('wagtail.blocks.RichTextBlock', (), {'editor': 'default', 'help_text': 'Add description', 'required': False}), 14: ('wagtail.blocks.StructBlock', [[('heading', 0), ('description', 13)]], {}), 15: ('wagtail.blocks.CharBlock', (), {'help_text': 'enter title', 'required': False}), 16: ('wagtail.blocks.ChoiceBlock', [], {'blank': True, 'choices': [('text', 'Text Menu'), ('bordered_button', 'Bordered Button Menu'), ('filled_button', 'Filled Button Menu')], 'help_text': 'Menu type', 'max_length': 20, 'null': True}), 17: ('wagtail.blocks.CharBlock', (), {'required': True}), 18: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('internal', 'Internal Page'), ('external', 'External URL')]}), 19: ('wagtail.blocks.PageChooserBlock', (), {'page_type': [], 'required': False}), 20: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Enter a unique key for this tab. This key will be used to link the                                                                                             menu to the corresponding section of the page.', 'label': 'Tab Key', 'required': False}), 21: ('wagtail.blocks.URLBlock', (), {'required': False}), 22: ('wagtail.blocks.CharBlock', (), {'editable': False, 'help_text': 'This field can be avoided and will be set automatically.', 'label': 'Page name(internal)', 'max_length': 150, 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('title', 17), ('link_type', 18), ('internal_page', 19), ('tab_key', 20), ('external_url', 21), ('internal_page_model_name', 22)]], {}), 24: ('wagtail.blocks.StructBlock', [[('title', 15), ('menu_type', 16), ('menu_item', 23), ('heading', 0)]], {}), 25: ('wagtail.blocks.StructBlock', [[('heading', 0), ('street', 1), ('phone', 2), ('email', 3), ('social_media', 12), ('right_part', 14), ('Middle_block', 24)]], {})})),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
