# Generated by Django 5.0.9 on 2024-10-30 05:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0026_delete_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('course_title', models.CharField(max_length=255)),
                ('course_week', models.CharField(max_length=255)),
                ('student_count', models.CharField(max_length=255)),
                ('course_description', models.TextField()),
                ('rating', models.CharField(max_length=3)),
                ('category', wagtail.fields.StreamField([('category', 1), ('levels', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'category name', 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('name', 0)]], {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'level name', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('name', 2)]], {})}, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Course Page',
                'verbose_name_plural': 'Course Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
