# Generated by Django 5.0.9 on 2024-10-30 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='rating',
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='course_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='course_week',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='student_count',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
