# Generated by Django 5.0.9 on 2024-10-30 05:58

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_remove_coursepage_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepage',
            name='levels',
            field=wagtail.fields.StreamField([('level', 0)], blank=True, block_lookup={0: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')]})}, null=True),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='category',
            field=wagtail.fields.StreamField([('category', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'category name', 'required': True}), 1: ('wagtail.blocks.StructBlock', [[('name', 0)]], {})}, null=True),
        ),
    ]
