# Generated by Django 5.0.9 on 2024-10-30 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_coursepage_levels_alter_coursepage_category'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Course Index Page',
                'verbose_name_plural': 'Course Index Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
