# Generated by Django 5.0.9 on 2024-10-30 07:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_alter_courseindexpage_intro_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='images',
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='category',
            field=wagtail.fields.StreamField([('category', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'category name', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Main image of the slider', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1)]], {})}, null=True),
        ),
    ]
