# Generated by Django 5.0.9 on 2024-10-30 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_remove_coursepage_images_alter_coursepage_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseIndexPage',
        ),
    ]
