# Generated by Django 5.0.9 on 2024-10-30 08:59

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_category_coursepage_images_alter_coursepage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='course_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
