# Generated by Django 5.0.9 on 2024-10-30 09:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0010_coursepage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='content',
            field=wagtail.fields.StreamField([('Body', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'name of instructor', 'max_length': 255}), 1: ('wagtail.blocks.URLBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'name of topic', 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('topic', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {'help_text': 'Add key topics section', 'label': 'Add topics', 'max_num': 10, 'min_num': 0}), 5: ('wagtail.blocks.StructBlock', [[('instructor', 0), ('link', 1), ('key_topic', 4)]], {})}, null=True),
        ),
    ]
